In [46]:
import cv2
import numpy as np
from scipy.io import loadmat
from matplotlib import pyplot
import cv2

In [47]:
data = loadmat('ex3data1.mat')
X, y = data['X'], data['y'].ravel()
print(X)
y[y == 10] = 0

m = y.size

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [48]:
weights = loadmat('ex3weights.mat')
Theta1, Theta2 = weights['Theta1'], weights['Theta2']
Theta2 = np.roll(Theta2, 1, axis=0)

In [49]:
def sigmoid(z):
    return (1 / (1 + np.exp( - z)))

In [50]:
print(Theta1.shape)
print(Theta2.shape)
print(X.shape)
input_layer = 400
hidden_layer = 25
output_layer = 10


(25, 401)
(10, 26)
(5000, 400)


In [51]:
def displayData(X, example_width=None, figsize=(10, 10)):
    """
    Displays 2D data stored in X in a nice grid.
    """
    # Compute rows, cols
    if X.ndim == 2:
        m, n = X.shape
    elif X.ndim == 1:
        n = X.size
        m = 1
        X = X[None]  # Promote to a 2 dimensional array
    else:
        raise IndexError('Input X should be 1 or 2 dimensional.')

    example_width = example_width or int(np.round(np.sqrt(n)))
    example_height = n / example_width

    # Compute number of items to display
    display_rows = int(np.floor(np.sqrt(m)))
    display_cols = int(np.ceil(m / display_rows))

    fig, ax_array = pyplot.subplots(display_rows, display_cols, figsize=figsize)
    fig.subplots_adjust(wspace=0.025, hspace=0.025)

    ax_array = [ax_array] if m == 1 else ax_array.ravel()

    for i, ax in enumerate(ax_array):
        ax.imshow(X[i].reshape(example_width, example_width, order='F'),
                  cmap='Greys', extent=[0, 1, 0, 1])
        ax.axis('off')

In [59]:
def predict(X):
    m = 1
    X = np.concatenate([np.ones((m, 1)), X], axis=1)
    hidden = sigmoid(X.dot(Theta1.T))
    hidden = np.concatenate([np.ones((m, 1)), hidden], axis = 1)
    Y = np.argmax(sigmoid(hidden.dot(Theta2.T)), axis = 1)
    return Y

In [60]:
print("O")

O


In [61]:
X1 = cv2.imread('output.jpg', 0)
X1 = X1.ravel()
X1 = X1 / 255
X1 = np.array(X1)
X1 = [X1]

In [ ]:
pred = predict(X1)
print(pred)
displayData(X)